apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-configmap
  namespace: {{ include "common.namespace" . }}
  labels:
    release: {{ .Release.Name }}
{{ include "common.labels" . | nindent 4 }}
data:
  # This should be secrets / env variables that we do not want to protect via encoding
  CACHE_DRIVER: "file"
  FILESYSTEM_DISK: "local"
