apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-deployment
  namespace: {{ include "common.namespace" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{ include "common.selectorLabels" . | nindent 8 }}
  strategy:
    type: {{ .Values.config.strategy.type }}
    rollingUpdate:
        maxSurge: {{ .Values.config.strategy.maxSurge | default 2 }}
        maxUnavailable: {{ .Values.config.strategy.maxUnavailable }}
  template:
    metadata:
      labels:
        name: {{ include "common.fullname" . }}-deployment
        {{ include "common.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http-phpfpm
            containerPort: {{ .Values.config.phpService.targetPort }}
            protocol: TCP
        envFrom:
          - secretRef:
              name: {{ include "common.fullname" . }}-env
          - configMapRef:
              name: {{ include "common.fullname" . }}-configmap
      - name: php-fpm-exporter
        image: "ghcr.io/hipages/php-fpm_exporter:latest"
        ports:
        - containerPort: 9253
        env:
        - name: PHP_FPM_WEB_LISTEN_ADDRESS
          value: :9253
        - name: PHP_FPM_WEB_TELEMETRY_PATH
          value: /metrics
        - name: PHP_FPM_SCRAPE_URI
          value: tcp://127.0.0.1/status
        - name: PHP_FPM_FIX_PROCESS_COUNT
          value: "false"
        - name: PHP_FPM_LOG_LEVEL
          value: info
