apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-deployment
  namespace: {{ include "common.namespace" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{ include "common.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        name: {{ include "common.fullname" . }}-deployment
        {{ include "common.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http-phpfpm
            containerPort: {{ .Values.config.phpService.targetPort }}
            protocol: TCP
        envFrom:
          - secretRef:
              name: {{ include "common.fullname" . }}-env
          - configMapRef:
              name: {{ include "common.fullname" . }}-configmap
