apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-ingress-configmap
  namespace: {{ include "common.namespace" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  SCRIPT_FILENAME: "/var/www/html/public$fastcgi_script_name"
  root: /var/www/html/public

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}-ingress
  namespace: {{ include "common.namespace" . }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host.name }}
    http:
      paths:
      - path: {{ .Values.ingress.host.path }}
        pathType: {{ .Values.ingress.host.pathType }}
        backend:
          service:
            name: {{ include "common.fullname" . }}-service
            port:
              number: {{ .Values.config.ports.targetPort }}
