apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ .Values.config.name }}-secretstore"
  namespace: {{ .Values.config.namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .Values.config.name }}-secrets"
  namespace: {{ .Values.config.namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: "{{ .Values.config.name }}-secretstore"
    kind: SecretStore
  target:
    name: "{{ .Values.config.name }}-env"
  dataFrom:
    - extract:
        key: cti-env-list
        decodingStrategy: Auto
