# This is not needed for use within GitLab due to service accounts.
#https://external-secrets.io/v0.7.0-rc1/provider/aws-secrets-manager/#eks-service-account-credentials

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "common.fullname" . }}-secretstore
  namespace: {{ include "common.namespace" .}}
  labels:
    release: {{ .Release.Name }}
{{ include "common.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region | default "eu-west-1" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access
            namespace: default
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret
            namespace: default

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-secret
  namespace: {{ include "common.namespace" . }}
  labels:
    release: {{ .Release.Name }}
{{ include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ include "common.fullname" . }}-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ include "common.fullname" . }}-env
  dataFrom:
    - extract:
        key: {{ .Values.secrets.key }}
        decodingStrategy: {{ .Values.secrets.decodingStrategy }}
