apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "common.fullname" . }}-secretstore
  namespace: {{ include "common.namespace" .}}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-secret
  namespace: {{ include "common.namespace" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ include "common.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "common.fullname" . }}-env
  dataFrom:
    - extract:
        key: cti-env-list
        decodingStrategy: Auto
