# Default values for helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Development Environment.
local: true

# Project Details.
project: CTI
name: Backend

# Project Environment
env: production

# Image Details.
image:
    repository: ghcr.io/ravelin/laravel-docker
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: sha-02f9471

# AWS Details.
aws:
    region: eu-west-2

config:
    ports:
        port: 80
        targetPort: 9000
    phpService:
        type: NodePort
        targetPort: 9000
    replicaCount: 2

ingress:
    host:
        path: /
        pathType: Prefix
        name: prd.test
    type: LoadBalancer


localIngress:
    ingressClass: nginx
    annotations:
        kubernetes.io/ingress.allow-http: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
        nginx.ingress.kubernetes.io/fastcgi-index: "index.php"

awsIngress:
    ingressClass: alb
    annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/backend-protocol: HTTPS
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/scheme: internet-facing

autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    targetMemoryUtilizationPercentage: 50
