# Default values for helm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
    repository: ghcr.io/ravelin/laravel-docker:sha-02f9471
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

aws:
    region: eu-west-2

config:
    environment: qa
    name: cti-backend-qa
    namespace: cti-qa
    ingress:
        host:
            path: /
            pathType: Prefix
            url: qa.test
        type: LoadBalancer
        env: qa
        annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/backend-protocol: HTTPS
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/scheme: internet-facing
        ingressClass: nginx
    ports:
        port: 80
        targetPort: 9000
    phpService:
        type: NodePort
        targetPort: 9000

autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetMemoryUtilizationPercentage: 50
