apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.config.name }}-service"
  namespace: {{ .Values.config.namespace }}
  labels:
    app: {{ .Values.config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.config.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.config.ports.targetPort }}
      targetPort: {{ .Values.config.ports.targetPort }}
      name: fastcgi
