apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-service
  namespace: {{ include "common.namespace" . }}
  labels:
    release: {{ .Release.Name }}
{{ include "common.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      name: fastcgi
  selector: {{ include "common.selectorLabels" . | nindent 4 }}
